In [65]:
import numpy as np
from scipy.optimize import linprog

In [66]:
factories = 5

In [67]:
ship_prices = np.array([84, 36, 42, 81, 63, 60, 66, 78, 15, 42, 
                                    63, 48, 33, 24, 33, 21, 33, 33, 60, 60,
                                    63, 18, 33, 66, 45, 45, 51, 60, 9, 24,
                                    39, 33, 57, 63, 42, 51, 45, 51, 45, 15,
                                    30, 21, 42, 42, 24, 33, 24, 33, 39, 12])

In [68]:
variables = len(ship_prices)

In [69]:
reserves = np.array([290, 165, 235, 255, 105])

In [70]:
demand = np.array([90, 65, 45, 75, 95, 100, 75, 150, 150, 205])

In [71]:
def matrix_of_reserves_limitations(factories, variables):
    
    res = np.zeros(shape=(factories, variables), dtype=int)
    count = variables / factories     #count = 10
    
    for index in range(0, factories):
        begin = count * index   #откуда начинать
        temp = np.zeros(variables)
        temp[int(begin):int(begin+count)] = 1
        res[index] = temp
        
        
    return res

In [72]:
limitations_to_reserves=matrix_of_reserves_limitations(factories, variables)
limitations_to_reserves

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1]])

In [83]:
def matrix_of_demand_limitations(factories, variables):
    count = int(variables / factories)
    res = np.zeros(shape=(count, variables), dtype=int) #пустая матрица из 0         
    begin = 0
    while begin < 9:
        for index in range(begin,count):
            temp = np.zeros(variables, dtype=int)
            indexTemp = 0
            for index2 in range(begin,variables,count):
                temp[int(indexTemp)+begin] = 1
                indexTemp += count
            begin+=1
            res[index] = temp
    return res

In [84]:
limitations_to_demand=matrix_of_demand_limitations(factories, variables)
limitations_to_demand

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0

In [116]:
result=linprog(c=ship_prices, 
              A_ub=limitations_to_reserves, b_ub=reserves,
              A_eq=limitations_to_demand, b_eq=demand,method='simplex')


In [134]:
lst=[]
for i in list(result['x']):
    lst.append(int(i))

In [118]:
np.reshape(lst,(5,10))

array([[  0,   0,  45,   0,   0,  95,   0,   0, 150,   0],
       [  0,   0,   0,  75,   0,   0,   0,  90,   0,   0],
       [  0,  65,   0,   0,  95,   5,  30,   0,   0,  40],
       [ 90,   0,   0,   0,   0,   0,   0,   0,   0, 165],
       [  0,   0,   0,   0,   0,   0,  45,  60,   0,   0]])

In [135]:
lst2=[]
for i in range(50):
    lst2.append(ship_prices[i]*lst[i])

In [137]:
sum(lst2)

31815

In [130]:
lst[0]

0